<div align="center"><a href="https://www.nvidia.com/en-us/deep-learning-ai/education/"><img src="./images/DLI_Header.png"></a></div>

# Introduction to Content-Based Filtering

[Content-based filtering](http://recommender-systems.org/content-based-filtering/) is a simple and effective way to recommend items based on a single user's previous feedback. It works by comparing the categories of an item, such as genres for movies or properties of clothing.

## Objective
This notebook demonstrates:
* How to build a content-based filter
  * [1. A Sweet Example](#1.-A-Sweet-Example)
  * [2. Building a Content-Based Filter](#2.-Building-a-Content-Based-Filter)
* How to use a content-based filter for recommendation
  * [3. Making Predictions](#3.-Making-Predictions)
  * [4. Wrap Up](#4.-Wrap-Up)

## 1. A Sweet Example

Let's look at a toy example with candies. The example below is what's called a user-item interaction matrix, where rows represent users, columns represent items, and the cells represent how the respective user interacted with the respective item. In this case, the users have scored the candies they've tried on a 1 star to 5 star scale. Dashes, `-`, represent items they haven't had yet.

User | M&Ms | Skittles | Snickers | Laffy Taffy | Caramel Chew
-|-|-|-|-|-
Lara| 3 | - | 5 | - | -
Daisy| 4 | - | - | 1 | -
Alyx | - | - | - | - | 5
Sarah | - | 3 | 2 | - | -

Let's say we consult our subject matter experts to categorize and label these candies. They might give us another table that looks like this:

Candy | Chocolate | Round | Colorful | Fruity | Caramel | Chewy
- | - | - | - | - | - | -
M&Ms | 1 | 1 | 1 | 0 | 0 | 0
Skittles | 0 | 1 | 1 | 1 | 0 | 0
Snickers | 1 | 0 | 0 | 0 | 1 | 0
Laffy Taffy | 0 | 0 | 1 | 1 | 0 | 1
Caramel Chew | 0 | 0 | 0 | 0 | 1 | 1 |

There are many ways to build a content-based filter, but one quick and effective way is by finding the user's percent preference per category.

## 2. Building a Content-Based Filter

<img src="images/bayesian.png" width="500" height="500">

Let's start by loading our toy problem into a CUDA Data Frame using [cuDF](https://docs.rapids.ai/api/cudf/stable/), which is a drop-in replacement library for pandas that executes on the GPU as opposed to the CPU.

In [2]:
import cudf

ratings = cudf.DataFrame({
    'user': ["Lara", "Lara", "Daisy", "Daisy", "Alyx", "Sarah", "Sarah"],
    'item': ["m_ms", "snickers", "m_ms", "laffy_taffy", "caramel_chew", "skittles", "snickers"],
    'rating': [3, 5, 4, 1, 5, 3, 2]})

ratings

user          item  rating
0   Lara          m_ms       3
1   Lara      snickers       5
2  Daisy          m_ms       4
3  Daisy   laffy_taffy       1
4   Alyx  caramel_chew       5
5  Sarah      skittles       3
6  Sarah      snickers       2

In [3]:
categories = cudf.DataFrame({
    'item': ["m_ms", "skittles", "snickers", "laffy_taffy", "caramel_chew"],
    'chocolate': [1, 0, 1, 0, 0],
    'round': [1, 1, 0, 0, 0],
    'colorful': [1, 1, 0, 1, 0],
    'fruity': [0, 1, 0, 1, 0],
    'caramel': [0, 0, 1, 0, 1],
    'chewy': [0, 0, 1, 1, 1]})

categories

item  chocolate  round  colorful  fruity  caramel  chewy
0          m_ms          1      1         1       0        0      0
1      skittles          0      1         1       1        0      0
2      snickers          1      0         0       0        1      1
3   laffy_taffy          0      0         1       1        0      1
4  caramel_chew          0      0         0       0        1      1

We can join these DataFrames with [merge](https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.merge.html) so we can find each user's preference for a category.

In [4]:
joined_ratings = ratings.merge(categories, on="item", how="left")

joined_ratings

user          item  rating  chocolate  round  colorful  fruity  caramel  \
0   Lara          m_ms       3          1      1         1       0        0   
1   Lara      snickers       5          1      0         0       0        1   
2  Daisy          m_ms       4          1      1         1       0        0   
3  Daisy   laffy_taffy       1          0      0         1       1        0   
4   Alyx  caramel_chew       5          0      0         0       0        1   
5  Sarah      skittles       3          0      1         1       1        0   
6  Sarah      snickers       2          1      0         0       0        1   

   chewy  
0      0  
1      1  
2      0  
3      1  
4      1  
5      0  
6      1

To make a Content-Based Filter, we'll start by multiplying each user's rating by the category for the item that rating belongs to.

In [5]:
candy_classes = ['chocolate', 'round', 'colorful', 'fruity', 'caramel', 'chewy']

for candy_class in candy_classes:
    joined_ratings[candy_class] = (
        joined_ratings[candy_class] * joined_ratings["rating"])

joined_ratings

user          item  rating  chocolate  round  colorful  fruity  caramel  \
0   Lara          m_ms       3          3      3         3       0        0   
1   Lara      snickers       5          5      0         0       0        5   
2  Daisy          m_ms       4          4      4         4       0        0   
3  Daisy   laffy_taffy       1          0      0         1       1        0   
4   Alyx  caramel_chew       5          0      0         0       0        5   
5  Sarah      skittles       3          0      3         3       3        0   
6  Sarah      snickers       2          2      0         0       0        2   

   chewy  
0      0  
1      5  
2      0  
3      1  
4      5  
5      0  
6      2

We can then use [groupby](https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.groupby.html) to sum the columns for each user to find the total number of points given to each category. We can also drop the `rating` column as we won't need it anymore.

In [6]:
user_profiles = joined_ratings.drop("rating", axis=1)
user_profiles = user_profiles.groupby(['user']).sum()

user_profiles

chocolate  round  colorful  fruity  caramel  chewy
user                                                     
Alyx           0      0         0       0        5      5
Daisy          4      4         5       1        0      1
Lara           8      3         3       0        5      5
Sarah          2      3         3       3        2      2

The goal of this filtering method is to find the user's percent preference for each category, so for that, we'll need the total amount of points given across every category for each user.

In [7]:
user_profiles["total"] = user_profiles[candy_classes].sum(axis=1)

user_profiles

chocolate  round  colorful  fruity  caramel  chewy  total
user                                                            
Alyx           0      0         0       0        5      5     10
Daisy          4      4         5       1        0      1     15
Lara           8      3         3       0        5      5     24
Sarah          2      3         3       3        2      2     15

Finally, we can divide each category by the total to get a user's percentage preference for each class.

In [8]:
for candy_class in candy_classes:
    user_profiles[candy_class] = (
        user_profiles[candy_class] / user_profiles["total"])
    
user_profiles = user_profiles.drop("total", axis=1)

user_profiles

chocolate     round  colorful    fruity   caramel     chewy
user                                                              
Alyx    0.000000  0.000000  0.000000  0.000000  0.500000  0.500000
Daisy   0.266667  0.266667  0.333333  0.066667  0.000000  0.066667
Lara    0.333333  0.125000  0.125000  0.000000  0.208333  0.208333
Sarah   0.133333  0.200000  0.200000  0.200000  0.133333  0.133333

## 3. Making Predictions

We can use these percentages to make new recommendations. For instance, Alyx has only had one candy: Caramel Chews. We can multiply her user profile across an item's categories to see what her predicted rating would be for that item.

With [CuPy](https://cupy.chainer.org/), we can efficiently do this for all users at once! CuPy is a GPU array library inspired by [NumPy](https://numpy.org/). Let's convert our DataFrames to CuPy arrays following the [conversion guide](https://docs.rapids.ai/api/cudf/stable/user_guide/10min-cudf-cupy.html).

In [9]:
import cupy as cp

user_profiles_cupy = cp.fromDlpack(user_profiles.to_dlpack())

user_profiles_cupy

/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/dlpack.py:74: UserWarning: WARNING: cuDF to_dlpack() produces column-major (Fortran order) output. If the output tensor needs to be row major, transpose the output of this function.
  return libdlpack.to_dlpack(gdf_cols)


array([[0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.5       ],
       [0.26666667, 0.26666667, 0.33333333, 0.06666667, 0.        ,
        0.06666667],
       [0.33333333, 0.125     , 0.125     , 0.        , 0.20833333,
        0.20833333],
       [0.13333333, 0.2       , 0.2       , 0.2       , 0.13333333,
        0.13333333]])

In [10]:
categories_cupy = cp.fromDlpack(categories.drop("item", axis=1).to_dlpack())

categories_cupy

array([[1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1]])

Let's make a prediction for one user first. We can take Alyx's profile and multiply it with the categories for each item.

In [11]:
alyx_ratings = user_profiles_cupy[0] * categories_cupy

alyx_ratings

array([[0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0.5, 0.5]])

Then, we can [sum](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.sum.html) each row to see the predicted preference for that corresponding row's item.

In [12]:
alyx_ratings = cp.sum(alyx_ratings, axis=1)

alyx_ratings

array([0. , 0. , 1. , 0.5, 1. ])

Here, Alyx would get a high rating for Snickers and Caramel Chews, but low ratings for M&Ms and Skittles.

Now, let's do this for everyone. We can be efficient with our data by using [NumPy](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) broadcasting rules.

`user_profiles_cupy` and `categories_cupy` are 4x6 and 5x6 respectively. If we try to multiply them without doing anything, CuPy will give us a dimension mismatch error. We can use [cupy.expand_dims](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.expand_dims.html) to make `user_profiles_cupy` 4x1x6. CuPy can then match the 1 to `categories_cupy`'s 5, and will multiply each user profile against each item's category listing, which is exactly what we need.

Since we have an extra dimension now, we'll do the sum against axis 2 instead of axis 1. We can verify that it worked because the first row will be the same as Alyx's prediction above.

In [13]:
preferences = cp.expand_dims(user_profiles_cupy, axis=1) * categories_cupy
preferences = cp.sum(preferences, axis=2)

preferences

array([[0.        , 0.        , 1.        , 0.5       , 1.        ],
       [0.86666667, 0.66666667, 0.33333333, 0.46666667, 0.06666667],
       [0.58333333, 0.25      , 0.75      , 0.33333333, 0.41666667],
       [0.53333333, 0.6       , 0.4       , 0.53333333, 0.26666667]])

This is equivalent to taking the dot product.

In [14]:
preferences = cp.dot(user_profiles_cupy, categories_cupy.transpose())
preferences

array([[0.        , 0.        , 1.        , 0.5       , 1.        ],
       [0.86666667, 0.66666667, 0.33333333, 0.46666667, 0.06666667],
       [0.58333333, 0.25      , 0.75      , 0.33333333, 0.41666667],
       [0.53333333, 0.6       , 0.4       , 0.53333333, 0.26666667]])

To get a predicted rating, we can scale these results by the same scale the users can use to rate items. If it's 1 - 5 stars, then we can multiply the range (5-1), and add the minimum rating (1).

In [15]:
min_rating = 1
max_rating = 5
preferences = preferences * (max_rating - min_rating) + min_rating

preferences

array([[1.        , 1.        , 5.        , 3.        , 5.        ],
       [4.46666667, 3.66666667, 2.33333333, 2.86666667, 1.26666667],
       [3.33333333, 2.        , 4.        , 2.33333333, 2.66666667],
       [3.13333333, 3.4       , 2.6       , 3.13333333, 2.06666667]])

It's time to bring it all together. Let's create a DataFrame to match each predicted rating to each user-item combo. Because we were careful to preserve order during the operations above, we can use [MultiIndex.from_product](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.MultiIndex.from_product.html) in order to build a DataFrame for each user-item combination.

In [16]:
user_ids = user_profiles.index.to_series().to_array()
category_ids = categories["item"].to_array()
predictions = cudf.MultiIndex.from_product([user_ids, category_ids], names=["user", "item"])
predictions = cudf.DataFrame(index = predictions).reset_index()

predictions

user          item
0    Alyx          m_ms
1    Alyx      skittles
2    Alyx      snickers
3    Alyx   laffy_taffy
4    Alyx  caramel_chew
5   Daisy          m_ms
6   Daisy      skittles
7   Daisy      snickers
8   Daisy   laffy_taffy
9   Daisy  caramel_chew
10   Lara          m_ms
11   Lara      skittles
12   Lara      snickers
13   Lara   laffy_taffy
14   Lara  caramel_chew
15  Sarah          m_ms
16  Sarah      skittles
17  Sarah      snickers
18  Sarah   laffy_taffy
19  Sarah  caramel_chew

We can then use CuPy's [ravel](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ravel.html) function to flatten our predictions and add it as a column to our DataFrame.

In [17]:
predictions["predicted_rating"] = cp.ravel(preferences)

predictions

user          item  predicted_rating
0    Alyx          m_ms          1.000000
1    Alyx      skittles          1.000000
2    Alyx      snickers          5.000000
3    Alyx   laffy_taffy          3.000000
4    Alyx  caramel_chew          5.000000
5   Daisy          m_ms          4.466667
6   Daisy      skittles          3.666667
7   Daisy      snickers          2.333333
8   Daisy   laffy_taffy          2.866667
9   Daisy  caramel_chew          1.266667
10   Lara          m_ms          3.333333
11   Lara      skittles          2.000000
12   Lara      snickers          4.000000
13   Lara   laffy_taffy          2.333333
14   Lara  caramel_chew          2.666667
15  Sarah          m_ms          3.133333
16  Sarah      skittles          3.400000
17  Sarah      snickers          2.600000
18  Sarah   laffy_taffy          3.133333
19  Sarah  caramel_chew          2.066667

Excellent! We now have predictions for each user-item interaction combo. We can sort the ratings for each user and recommend their top X items. There's one last important piece of the puzzle in that we don't want to recommend something the user has rated before. Let's add in the original ratings to do this.

Before moving on to the next step, let's compare the predicted rating with the actual rating. How did we do? Note where the algorithm went well and where it didn't and try to come up with an explanation for why.

In [18]:
predictions = predictions.merge(ratings, how="left")

predictions

user          item  predicted_rating rating
0    Alyx  caramel_chew          5.000000      5
1   Daisy          m_ms          4.466667      4
2   Daisy   laffy_taffy          2.866667      1
3    Lara          m_ms          3.333333      3
4    Lara      snickers          4.000000      5
5   Sarah      skittles          3.400000      3
6   Sarah      snickers          2.600000      2
7    Alyx          m_ms          1.000000   <NA>
8    Alyx      skittles          1.000000   <NA>
9    Alyx      snickers          5.000000   <NA>
10   Alyx   laffy_taffy          3.000000   <NA>
11  Daisy      skittles          3.666667   <NA>
12  Daisy      snickers          2.333333   <NA>
13  Daisy  caramel_chew          1.266667   <NA>
14   Lara      skittles          2.000000   <NA>
15   Lara   laffy_taffy          2.333333   <NA>
16   Lara  caramel_chew          2.666667   <NA>
17  Sarah          m_ms          3.133333   <NA>
18  Sarah   laffy_taffy          3.133333   <NA>
19  Sarah  caramel_chew          2.066667   <NA>

Finally, we can use [loc](https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.loc.html) to locate the rows without a rating yet so we can serve recommendations to the user.

In [19]:
predictions.loc[predictions['rating'].isnull()].drop("rating", axis=1)

user          item  predicted_rating
7    Alyx          m_ms          1.000000
8    Alyx      skittles          1.000000
9    Alyx      snickers          5.000000
10   Alyx   laffy_taffy          3.000000
11  Daisy      skittles          3.666667
12  Daisy      snickers          2.333333
13  Daisy  caramel_chew          1.266667
14   Lara      skittles          2.000000
15   Lara   laffy_taffy          2.333333
16   Lara  caramel_chew          2.666667
17  Sarah          m_ms          3.133333
18  Sarah   laffy_taffy          3.133333
19  Sarah  caramel_chew          2.066667

## 4. Wrap Up

We didn't split the data into train and test because our example here is too small, so using a larger dataset is bound to introduce some interesting challenges. Now that we have a system that works with synthetic data, let's test our new knowledge on the real thing. 

Feeling ready? Please run the cell below to shut down the kernel before moving on to the <a href="1-04_content_based_real_data.ipynb">next notebook</a>.

In [20]:
import IPython

app = IPython.Application.instance()
app.kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

<div align="center"><a href="https://www.nvidia.com/en-us/deep-learning-ai/education/"><img src="./images/DLI_Header.png"></a></div>